# Generated by Django 5.2 on 2025-07-10 00:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hoteluser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hotelvendor',
            options={},
        ),
        migrations.AddField(
            model_name='hotelvendor',
            name='business_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='hoteluser',
            table='Hotel User',
        ),
        migrations.AlterModelTable(
            name='hotelvendor',
            table='Hotel Vendor',
        ),
    ]
