# Generated by Django 5.2 on 2025-07-10 15:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='icon',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='amenities'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amenities',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
